#+OPTIONS: toc:nil
* elmguess
My Toy "Guess a Number" app written in [[http://elm-lang.org][Elm]].

** To Run This
- git clone
- run ~gulp~ (this gets a server going)
- navigate to ~http://localhost:4000~

** What I'm Trying to Accomplish

This is a simple app, for sure, and likely far too "toy" for anyone
who's done any amount of "modern", javascript based, frameworkey UI
work.  

I, however, am not that person. The last UI work I can say I've done
in earnest was with WebWork (the predecessor to Struts 2.x), and when
doing layout with ~<table>~ tags was still a thing. I still have a
website out there that is *making money* that is done in this way. The
only javascript it has is to do a popup when asked, and clear a text
field on focus. So, yeah.

But, I'm trying to learn.  So here I go.  As this is my first SPA of
any description, I have a lot to learn other than just Elm.  Here are
a few things I want to be able to handle, if even a little bit.

- Elm (the point of this)
- gulp (for the build)  Maybe buildpack as I go?
- CSS (for perhaps obvious reasons)
  
Please don't judge me too harshly; I know this is going to probably be
awful, but it's a learning exercise for me. I've just completed the
knowthen.com [[http://courses.knowthen.com/courses/elm-for-beginners][Elm course]] for beginners, which has an even more
complicated app than this as the example, but this is me doing the
layout and everything from scratch, rather than following along
someone else's work. Too, the course has pre-rolled CSS, and I don't,
so I'll be doing that from scratch too.

** What I Actually Accomplished
As I learn stuff, I'll document them here.

- [[https://scotch.io/tutorials/automate-your-tasks-easily-with-gulp-js][Did a gulp tutorial]]
  - Learned a bit about the ~http~ and ~st~ packages in npm.
  - and ~del~
- Came up with an emacs yasnippet template for the html to wrap an elm
  app. 
- Futzed around with CSS.  I know I need a lot of work here.  Going to
  ask some colleages for help/review.
- Realized that having a static html page to do the css work on first
  made it a lot easier as I went.
- I did all the code and had the output unstyled, then styled it last.
  Not sure if this was a good idea or not.
- Hacked up a way to get an initial seed for random numbers using a
  time subscription.  This is maddeningly hard.
- Undid my hacked up seed, and kind of figured out how to do this with a proper Task and
  Time.now.  It's still maddeningly hard.
